spring.application.name=project111
spring.datasource.url=jdbc:h2:mem:diemthidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
pring.h2.console.path=/h2-console